version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: your_root_password
    ports:
      - "8080:80"
    depends_on:
      - db  # Ensure phpmyadmin starts after db

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management plugin port

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  obs-api:
    image: huseyin72/obs_api:v1
    restart: always
    environment:
      DB_NAME: obs
      DB_USER: root
      DB_PASSWORD: your_root_password
      DB_HOST: db
      DB_PORT: 3306
      DB_DIALECT: mysql
      DB_LOGGING: false
      PORT: 4000
      SECRET_KEY: IMSapp
    depends_on:
      - db
      - phpmyadmin
      - rabbitmq
    ports:
      - "4000:4000" # Gereksinimlerinize göre ayarlayın


volumes:
  db_data:
  rabbitmq_data:
