version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: your_root_password
    ports:
      - "8080:80"
    depends_on:
      - db  # Ensure phpmyadmin starts after db

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nodeapp1:
    image: node:latest
    restart: always
    working_dir: /app
    command: sh -c "npm start"
    volumes:
      - ./CENG316-AUTH-SERVICE:/app
      - ../../ceng316-gateway/index.j # Assuming index.js is in this directory
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq

  nodeapp2:
    image: node:latest
    restart: always
    working_dir: /app
    command: sh -c "npm start"
    volumes:
      - ./CENG316-AUTH-SERVICE:/app
      - ../src/index.js # Assuming index.js is in this directory
    ports:
      - "3001:3000"
    depends_on:
      - db
      - rabbitmq

volumes:
  db_data:
  rabbitmq_data:
